name:                telBotGS
version:             0.1.0.0
github:              "darklordshish/telBotGS"
license:             BSD3
author:              "Semion"
maintainer:          "darkshish@gmail.com"
copyright:           "Copyright (c) 2022 Semion Shishkin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/darklordshish/telBotGS#readme>

dependencies:
- base >= 4.7 && < 5
- telegram-bot-simple
- text
- http-client
- http-client-tls
- servant-client
- random
- directory
- time
- mtl
- persistent
- persistent-postgresql
- persistent-template
- esqueleto
- monad-logger
- monad-control
- transformers
# - gogol
# - gogol-speech
# - gogol-core
# - aeson

library:
  source-dirs: src

executables:
  telBotGS-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - telBotGS

tests:
  telBotGS-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - telBotGS
